//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProjects.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStudent
    {
        public int StudentId { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<System.DateTime> EndDateOfStudent { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Student Student { get; set; }
    }
}
