//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProjects.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.ProjectStudents = new HashSet<ProjectStudent>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public int RecordBookNumber { get; set; }
        public int GroupId { get; set; }
        public int SpecialityId { get; set; }
        public int CathedraNumber { get; set; }
    
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectStudent> ProjectStudents { get; set; }
        public virtual Speciality Speciality { get; set; }
    }
}
